export const LIBRARY_PREFIX = "lucide";

export const AVAILABLE_ICONIFY_ICONS = {
  Check: "check",
  ChevronDown: "chevron-down",
  ChevronRight: "chevron-right",
  ChevronUp: "chevron-up",
  ChevronLeft: "chevron-left",
  Circle: "circle",
  Heart: "heart",
  Home: "home",
  Image: "image",
  LoaderCircle: "loader-circle",
  LogOut: "log-out",
  MapPin: "map-pin",
  Minus: "minus",
  MoreHorizontal: "more-horizontal",
  Menu: "menu",
  Search: "search",
  Slash: "slash",
  Stethoscope: "stethoscope",
  Close: "x",
  Plus: "plus",
  Eye: "eye",
  EyeOff: "eye-off",
  Lock: "lock",
  X: "x",
};
