/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authGuardImport } from './routes/(auth)/_guard'
import { Route as guestRegisterIndexImport } from './routes/(guest)/register/index'
import { Route as guestLoginIndexImport } from './routes/(guest)/login/index'
import { Route as authGuardIndexImport } from './routes/(auth)/_guard/index'
import { Route as authGuardAdminRouteImport } from './routes/(auth)/_guard/admin/route'
import { Route as authGuardDashboardIndexImport } from './routes/(auth)/_guard/dashboard/index'
import { Route as authGuardAdminIndexImport } from './routes/(auth)/_guard/admin/index'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const authGuardRoute = authGuardImport.update({
  id: '/_guard',
  getParentRoute: () => authRoute,
} as any)

const guestRegisterIndexRoute = guestRegisterIndexImport.update({
  id: '/(guest)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const guestLoginIndexRoute = guestLoginIndexImport.update({
  id: '/(guest)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authGuardIndexRoute = authGuardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authGuardRoute,
} as any)

const authGuardAdminRouteRoute = authGuardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authGuardRoute,
} as any)

const authGuardDashboardIndexRoute = authGuardDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authGuardRoute,
} as any)

const authGuardAdminIndexRoute = authGuardAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authGuardAdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_guard': {
      id: '/(auth)/_guard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authGuardImport
      parentRoute: typeof authRoute
    }
    '/(auth)/_guard/admin': {
      id: '/(auth)/_guard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authGuardAdminRouteImport
      parentRoute: typeof authGuardImport
    }
    '/(auth)/_guard/': {
      id: '/(auth)/_guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authGuardIndexImport
      parentRoute: typeof authGuardImport
    }
    '/(guest)/login/': {
      id: '/(guest)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(guest)/register/': {
      id: '/(guest)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof guestRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_guard/admin/': {
      id: '/(auth)/_guard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authGuardAdminIndexImport
      parentRoute: typeof authGuardAdminRouteImport
    }
    '/(auth)/_guard/dashboard/': {
      id: '/(auth)/_guard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authGuardDashboardIndexImport
      parentRoute: typeof authGuardImport
    }
  }
}

// Create and export the route tree

interface authGuardAdminRouteRouteChildren {
  authGuardAdminIndexRoute: typeof authGuardAdminIndexRoute
}

const authGuardAdminRouteRouteChildren: authGuardAdminRouteRouteChildren = {
  authGuardAdminIndexRoute: authGuardAdminIndexRoute,
}

const authGuardAdminRouteRouteWithChildren =
  authGuardAdminRouteRoute._addFileChildren(authGuardAdminRouteRouteChildren)

interface authGuardRouteChildren {
  authGuardAdminRouteRoute: typeof authGuardAdminRouteRouteWithChildren
  authGuardIndexRoute: typeof authGuardIndexRoute
  authGuardDashboardIndexRoute: typeof authGuardDashboardIndexRoute
}

const authGuardRouteChildren: authGuardRouteChildren = {
  authGuardAdminRouteRoute: authGuardAdminRouteRouteWithChildren,
  authGuardIndexRoute: authGuardIndexRoute,
  authGuardDashboardIndexRoute: authGuardDashboardIndexRoute,
}

const authGuardRouteWithChildren = authGuardRoute._addFileChildren(
  authGuardRouteChildren,
)

interface authRouteChildren {
  authGuardRoute: typeof authGuardRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authGuardRoute: authGuardRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authGuardIndexRoute
  '/admin': typeof authGuardAdminRouteRouteWithChildren
  '/login': typeof guestLoginIndexRoute
  '/register': typeof guestRegisterIndexRoute
  '/admin/': typeof authGuardAdminIndexRoute
  '/dashboard': typeof authGuardDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authGuardIndexRoute
  '/login': typeof guestLoginIndexRoute
  '/register': typeof guestRegisterIndexRoute
  '/admin': typeof authGuardAdminIndexRoute
  '/dashboard': typeof authGuardDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_guard': typeof authGuardRouteWithChildren
  '/(auth)/_guard/admin': typeof authGuardAdminRouteRouteWithChildren
  '/(auth)/_guard/': typeof authGuardIndexRoute
  '/(guest)/login/': typeof guestLoginIndexRoute
  '/(guest)/register/': typeof guestRegisterIndexRoute
  '/(auth)/_guard/admin/': typeof authGuardAdminIndexRoute
  '/(auth)/_guard/dashboard/': typeof authGuardDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/register' | '/admin/' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/admin' | '/dashboard'
  id:
    | '__root__'
    | '/(auth)'
    | '/(auth)/_guard'
    | '/(auth)/_guard/admin'
    | '/(auth)/_guard/'
    | '/(guest)/login/'
    | '/(guest)/register/'
    | '/(auth)/_guard/admin/'
    | '/(auth)/_guard/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
  guestLoginIndexRoute: typeof guestLoginIndexRoute
  guestRegisterIndexRoute: typeof guestRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
  guestLoginIndexRoute: guestLoginIndexRoute,
  guestRegisterIndexRoute: guestRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)",
        "/(guest)/login/",
        "/(guest)/register/"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_guard"
      ]
    },
    "/(auth)/_guard": {
      "filePath": "(auth)/_guard.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_guard/admin",
        "/(auth)/_guard/",
        "/(auth)/_guard/dashboard/"
      ]
    },
    "/(auth)/_guard/admin": {
      "filePath": "(auth)/_guard/admin/route.tsx",
      "parent": "/(auth)/_guard",
      "children": [
        "/(auth)/_guard/admin/"
      ]
    },
    "/(auth)/_guard/": {
      "filePath": "(auth)/_guard/index.tsx",
      "parent": "/(auth)/_guard"
    },
    "/(guest)/login/": {
      "filePath": "(guest)/login/index.tsx"
    },
    "/(guest)/register/": {
      "filePath": "(guest)/register/index.tsx"
    },
    "/(auth)/_guard/admin/": {
      "filePath": "(auth)/_guard/admin/index.tsx",
      "parent": "/(auth)/_guard/admin"
    },
    "/(auth)/_guard/dashboard/": {
      "filePath": "(auth)/_guard/dashboard/index.tsx",
      "parent": "/(auth)/_guard"
    }
  }
}
ROUTE_MANIFEST_END */
